puppetlabs/clj-i18n

- project.clj
This commit sets the version back to `0.2.1-SNAPSHOT` so that we can
release `0.2.1` to Clojars and fixes up some of the other miscellaneous
fields in the project.clj like `:url` and `:license`. This commit also
changes the repositories so that our Jenkins job will deploy to Clojars.
> (maint) Prep clj-i18n for initial clojars release

- README.md
This commit adds a Clojars badge for the latest Clojars version of the
project to the README as well as a gitignore example. This commit also
does some generic tidying up of the README.
> (maint) Update README with Clojars badge

- src/leiningen/i18n/Makefile
This behaves differently on different platforms, causing meaningless changes
to the messages.pot file. On OS X, `find src/` lists files with two slashes,
whereas on linux it lists them with a single slash. Both use a single slash if
the slash is omitted from the command.
> Remove trailing slash from `src` in find command

- README.md
I believe `brew link --force` will link *all* keg-only formula, which could cause some issues.
> (maint) include more details on homebrew install for OSX

- README.md
- locales/de.po
- locales/messages.pot
- project.clj
- src/leiningen/i18n/Makefile
- src/puppetlabs/i18n/core.clj
- src/puppetlabs/i18n/main.clj
- test/puppetlabs/i18n/core_test.clj
This adds two new functions trun and trsn that support pluralization.  They mirror the
ngettext function in behavior, while keeping the convention of java formatting.
Examples and tests were updated as well.
> Add support for pluralization string extraction and use

- src/puppetlabs/i18n/core.clj
This fixes the ```lookup-plural``` function to return the plural message id in case the translation is not found and the count is not equal to 1.
Previously it always returned the singular message id.
> (maint) Fix lookup-plural function

- README.md
- dev-resources/test-locales/conflicting-de.clj
- dev-resources/test-locales/de-ru-es.clj
- dev-resources/test-locales/fr-it.clj
- dev-resources/test-locales/merge-eo.clj
- dev-resources/test-locales/multi-pacakge-es.clj
- locales/de.po
- locales/messages.pot
- src/leiningen/i18n.clj
- src/leiningen/i18n/Makefile
- src/puppetlabs/i18n/core.clj
- test/puppetlabs/i18n/core_test.clj
Prior to this commit the ```:package``` key in the ```locales.clj``` file as generated by the Makefile was set to a value derived from the project name.
This didn't work at least for the following projects:
* [puppetlabs/pcp-common](https://github.com/puppetlabs/clj-pcp-common)
* [puppetlabs/pcp-client](https://github.com/puppetlabs/clj-pcp-client)
which don't use the assumed prefixes of ```puppetlabs.pcp_common``` and ```puppetlabs.pcp_client``` respectively for their namespaces but rather define different namespaces under the common root of ```puppetlabs.pcp```.
To be able to support that, this patch redefines the structure of the ```locales.clj``` such that it can now contain the ```:packages``` key (as opposed to the original ```:package```) which is expected to contain a collection …
> (INTL-1) Support for multiple packages in locales.clj

- README.md
- locales/de.po
- locales/messages.pot
- src/leiningen/i18n/Makefile
- src/puppetlabs/i18n/core.clj
- src/puppetlabs/i18n/main.clj
Previously, the only way to mark a string for extraction was to either
use a translation function or use a project-specific marker function and
update the make target accordingly. This commit provides a standard
i18n/mark function which has no behavior beyond returning its argument,
but which serves as a designated way to extract strings without
translating them.
This is important for cases where the string needs to be translated
dynamically but is defined at compile time. In particular, it allows for
commonly-used strings to be defined in a variables and used in multiple
places.
> (ORCH-1232) Add a standard function for marking strings for extraction

- src/leiningen/i18n/Makefile
This commit introduces a couple of fixes for problems in the Makefile:
* the dollar characters in the shell receipt for extracting the messages to be localized are now properly escaped
* the sed command is now invoked in a way that works on both Linux and Mac OS X (the previous way didn't work on Mac OS X due to a difference in handling of the sed's `-i` option argument between Linux and Mac OS X)
* the `-k` option is now passed to the `xgettext` to suppress accidental localization of clojure forms resembling some of the lisp forms localized by default
* the `-F` option is passed as `--sort-by-file` to `xgettext` to be more self explanatory
* the `messages.pot` file is touched even if not changed in case it is older than some of the clojure sources so that it is considered up-to-date the …
> (maint) Makefile fixes

- src/leiningen/i18n/Makefile
We used '>&' which works in bash, but breaks in other shells (like
dash). Instead, use a more standard separate redirection of stdout and
stderr.
> Makefile: fix bashism in target for locales/messages.pot

- src/leiningen/i18n/Makefile
A lot of distros out there, including CentOS 7, ship with an xgettext that
barfs on --add-location=file. Only pass that option if it is supported,
otherwise generate full location information.
> Makefile: only use the file value for --add-location if it is supported

- README.md
When working on i18n, we were having difficulty with having the translations show up because our namespaces did not match our project name. We read the README multiple times but always ended up glossing over the Project Setup section because our projects already ran smoothly without any errors. I thought that it would be a good idea to change #3 to be in bold font so that more attention can be called to it in case other people encounter this as well.
> Bolded #3 of Project Setup

- dev-resources/test-locales/overlapping-packages.clj
- src/puppetlabs/i18n/core.clj
- test/puppetlabs/i18n/core_test.clj
This commit switches bundle-for-namespace to use a cached copy of
info-map, rather than regenerating it on each call. Regenerating the
info-map on each translate call and use a lot of CPU and slow down users
of the library.
> (PDB-2985) Cache info-map to reduce CPU usage

- dev-resources/test-locales/overlapping-packages.clj
- src/puppetlabs/i18n/core.clj
- test/puppetlabs/i18n/core_test.clj
This commit changes the data structure of info-map back to a regular
hash-map. The sorted version was causing problems when two packages had
the same package name length. The sorting now takes place in
bundle-for-namespace, like it did previously.
> (INTL-7) Revert info-map's usage of sorted-map

- dev-resources/test-pos/diff-location.pot
- dev-resources/test-pos/diff-order.pot
- dev-resources/test-pos/diff-ref.pot
- dev-resources/test-pos/diff-string-edit.pot
- dev-resources/test-pos/diff-translated.pot
- dev-resources/test-pos/diff-whole-string.pot
- dev-resources/test-pos/git-ref.po
- dev-resources/test-pos/line-numbers.po
- dev-resources/test-pos/no-git-ref.po
- dev-resources/test-pos/no-line-numbers.po
- dev-resources/test-pos/no-project-id-version.po
- project.clj
- src/leiningen/i18n.clj
- src/leiningen/i18n/Makefile
- src/leiningen/i18n/bin/add-gitref.sh
- src/leiningen/i18n/bin/compare-POTs.sh
- src/leiningen/i18n/bin/remove-line-numbers.sh
- src/leiningen/i18n/bin/update-pot.sh
- test/puppetlabs/i18n/bin_test.clj
These commits add several scripts that facilitate automated updates of the `locals/messages.POT` file in CI. The main script is `src/leiningen/i18n/bin/update-pot.sh`, which moves the current POT out of the way, generates a new one, compares the strings between the two, and commits and pushes the new POT if it has different strings than the old one (after stripping any line numbers from the location comments and adding a header with the current git commit's SHA). If no string changes are found, the extant POT is restored.
This main script has no automated tests, but most of the work happens in the other scripts, all of which have clojure tests for their behavior in the `puppetlabs.i18n.bin-test` namespace. The main script has been tested by using it in an experimental CI job on Jenkins …
> (PE-15457) Scripts for CI POT Update Workflow

- src/leiningen/i18n/bin/update-pot.sh
It appears that [`realpath` is not uniformly available on our jenkins test runners](https://jenkins-enterprise.delivery.puppetlabs.net/job/enterprise_rbac_i18n-clj_2017.1.x/1/console).
> (maint) Don't use `realpath` in update-pot script

- project.clj
I didn't mean to bump it up to 0.6.0-SNAPSHOT with the release job.
> (maint) Bump version down to 0.5.2-SNAPSHOT

- src/puppetlabs/i18n/core.clj
- test/puppetlabs/i18n/core_test.clj
Prior to this commit we were defaulting the user-locale to message-locale
(i.e. "en"). This commit changes this behavior so that we default to
translating `i18n/tru` messages to system-locale translations if we have
them.
> (PE-18855) Default the user-locale to system-locale

- project.clj
This commit prepares the project.clj for a 0.6.0 release.
> (maint) Prepare for 0.6.0 release

- src/leiningen/i18n/Makefile
The creation of the English resource bundle `Messages_en.class` was
causing the POT file to still be updated via the default `msgfmt` target
that's invoked from the leiningen compile hook. This results in the POT
file still being automatically updated during development, which we
don't want now that there's a CI job that handles updating the POT file.
Rectify this by removing the `en` MESSAGE_LOCALE from all the locale
lists and removing the target to generate the `Messages_en.class`. Since
the library returns the original message when there's no bundle for
a locale, and all our messages are in the English locale already, this
should not cause a change in behavior.
Since this introduces the possibility of having an orphaned English
resource bundle that's never updated (because there's no …
> (maint) Don't create an English resource bundle

- src/puppetlabs/i18n/core.clj
- src/puppetlabs/i18n/main.clj
- test/puppetlabs/i18n/core_test.clj
Prior to this commit, if a string was empty, instead of an empty string in the class bundle, GNU gettext behavior is to print the header of the POT file. So where we would expect empty strings, the POT header would be printed instead.
With this commit if a msgid is an empty string, an empty string is returned.
> (PE-19745) Empty string should render an empty string not POT header.

- README.md
There was some handy information in confluence that isn't very easy to
find and reference when externalizing strings in clojure. This commit
copies it into the README to make it more accessible.
> (maint) Update README.md to include whitespace recommendations

- src/leiningen/i18n/Makefile
On initial bootstrapping of i18n it seems like the
clean-orphaned-bundles can get into a state where it tries to remove a
glob that doesn't exist. I think fixing the glob behavior would be
ideal, but as I don't have a good idea about that this commit adds a
check to see if the bundle exists before attempting to delete it.
```matthaus@wyclef-2  /Users/matthaus/src/pe-file-sync [hoyt]> lein i18n init
Setting up Makefile; don't forget to check it in
Adding i18n scripts in `dev-resources/i18n/bin`
matthaus@wyclef-2  /Users/matthaus/src/pe-file-sync [hoyt]> make i18n
Writing resources/locales.clj
matthaus@wyclef-2  /Users/matthaus/src/pe-file-sync [hoyt]> make i18n
rm: resources/puppetlabs/pe_file_sync/Messages_*.class: No such file or directory
make: *** [clean-orphaned-bundles] Error 1```
> (maint) Only delete bundle if it exists

- src/puppetlabs/i18n/core.clj
They are calling Java methods that will always return Strings, but the
Clojure compiler doesn't know that. It's pretty common to use a
translated string as a parameter to a java method/constructor. For
example `(throw (Exception. (trs "My translated string")))` will cause
a reflection warning. Type hints on the two underlying translate
functions will prevent that.
> Add type hints to the translate functions

- CHANGELOG.md
- README.md
- project.clj
In order to make the library more portable, this removes the AOT
specification for main, and the main entry in the project.clj
The README is updated with instructions to correctly run the
main example.
A CHANGELOG is also added to provide a brief summary of changes going forward.
> (maint) remove AOT compilation and main clause from project.clj
